services:
  db:
    image: postgres:12.19
    container_name: postgres-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./api/db/data:/var/lib/postgres/data
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fiap_challenge
    networks:
      - fiap-network

  api:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: api
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - fiap-network
    env_file:
      - path: .env
        required: true # default

networks:
  fiap-network:
    driver: bridge