version: "3.7"
services:
  db:
    image: postgres:12.19-bullseye
    container_name: postgres-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./api/db/data:/var/lib/postgres
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
  api:
    build: "."
    container_name: api
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - db